spring:
  jmx:
    enabled: false
#  datasource:
#    username: root
#    password: xxx000
#    url: jdbc:mysql://39.108.154.215:3306/poetry_union?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/poetry_union?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 120m
  port: 10086

logging:
  level:
    root: info

mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      id-type: AUTO
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.school.union,poetry.entity



